### ISSUE TITLE
[proposal] Default schemes for models in the project

### ISSUE THREAD

**Issue by vitalik** [vitalik/django-ninja#116]
Pretty often we just need to output a database object or a queryset of objects

And to do that need to do lot of manual work for every model (create schema, list fields, pass it as `response` argument)

the proposal is to define a map of default model schemes, which will be automatically resolved during response:

```Python
@api.default_responses({
    'app.Model': {'fields': ['id', 'name', 'timestamp']},
    'app.Related': {'fields': ['id', 'title']},
    Third: {'exclude': ['sensitive_field']},
    Forth: ManualScheme,
})


@api.get('/some')  # note !! - no response argument here
def some_endpoint(request):
    return Model.objects.all() # should work


@api.get('/some/{id}')
def some_endpoint(request, id: int):
    return Model.objects.get(id=id) # should work

@api.get('/some/related')
def some_endpoint(request):
    return Model.objects.select_related('related') # can this work as well including related object as nested ?
```

Pros: 

 - no need to define schemes
 -  no need to pass them to to `response` argument
 
Cons:

 - the response schema will be missing in openapi json (maybe some extra hint param will help)
 - pagination logic  is not clear

**Comment by gmso** [comment]
Hi @vitalik,

First of all thank you and all contributors for this awesome library, it's great!

Seeing this enhancement proposal you wrote, and with the spirit of trying to contribute myself to this project, I have lately been trying to find a solution to the enhancement proposed here.

I believe I have found a good solution for this use case: returning `QuerySet` or a single model instance from the view, without the need to define a `Schema` nor to use a `response` argument.

I did not approach it by having the need to define the mentioned `default_responses`, but instead having the response being all of the fields and objects present in the `QuerySet` or model instance. I hoped this would make the usage more simple, leaving more complicated schemes to the explicit creation of a `Schema` or `ModelSchema`.

Please let me know __if I should submit a pull request or if you prefer to discuss the implementation here before.__

I documented the solution (`django-querysets-and-models.md`) on my [fork of the project](https://github.com/gmso/django-ninja/tree/issue_116). But the summary is something like this:

## Example

Given the following example `Model`:

```Python
class Todo(models.Model):
    title = models.CharField(max_length=50)
    completed_at = models.DateTimeField(null=True, blank=True)
    goal = models.ForeignKey(Goal, null=True, blank=True, on_delete=models.CASCADE)
```

## Returning a QuerySet

If your view returns a `QuerySet` with all `Todo` objects in the database:

```Python
@router.get("/todos")
def get_all_todos(request):
    return Todo.objects.all()
```

The serialized HTTP response will correspond to a list of all fields found in the `QuerySet`, including the model's `Foreign Keys` (`goal` in this example) and reverse `OneToOne` relationships (`ranking` in this example):
```json
[
  {
    "ranking": {
        "id": 2,
        "position": 2
    },  
    "id": 1,
    "title": "Study italian",
    "completed_at": "2022-01-03T19:57:46Z",
    "goal": {
        "id": 1,
      "name": "Learn foreign languages"
    },
  },
  {
    "ranking": null,  
    "id": 2,
    ...
  }
  ...
]
```

## Returning a model instance

If your view returns a single model instance, it will be serialized as a JSON object. Considering the following view:

```Python
@router.get("/todos/{id}")
def get_todo_from_id(request, id: int):
    todo = get_object_or_404(Todo, pk=id)
    return todo
```

If called with `id=1`, the response will be:
```json
{
  "ranking": {
    "id": 2,
    "position": 2
  },
  "id": 1,
  "title": "Study italian",
  "completed_at": "2022-01-03T19:57:46Z",
  "goal": {
    "id": 1,
    "name": "Learn foreign languages"
  }
}
```

## Including related fields

If you need to return also related `ManyToMany` relationships (both direct and reverse), you can use Django's `prefetch_related` to fetch these fields before serialization ocurrs.

Considering that the `Todo` model has a reverse `ManyToMany` relationship with the `Tag` model:

```Python
class Tag(models.Model):
    name = models.CharField(max_length=30)
    todos = models.ManyToManyField(Todo)
```

If we add `prefetch_related` to the view in the first example:

```Python
@router.get("/todos/prefetched")
def get_all_todos_with_prefetch(request):
    return Todo.objects.all().prefetch_related("tag_set")
```

We should now have the `tag_set` included in the objects of the returned `QuerySet`

```json
[
  {
    "tag_set": [],
    "ranking": {
      "id": 2,
      "position": 2
    },
    "id": 1,
    "title": "Study italian",
    "completed_at": "2022-01-03T19:57:46Z",
    "goal": {
      "id": 1,
      "name": "Learn foreign languages"
    }
  },
  {
    "tag_set": [
      {
        "id": 2,
        "name": "Work"
      }
    ],
    "ranking": {
      "id": 1,
      "position": 1
    },
    "id": 2,
    "title": "Work on project A",
    "completed_at": "2022-01-04T09:16:07.230Z",
    "goal": null
  },
  ...
]
```

## Pagination

Pagination for `QuerySets` is also possible using slices:

```Python
@router.get("/todos/paginated")
def get_paginated_todos(request, page: int = 1):
    paginate_by = 2
    first = max(0, paginate_by * (page - 1))
    last = first + paginate_by
    return Todo.objects.all()[first:last]
```

**Comment by vitalik** [comment]
Hi @gmso 

yeah, converting queryset/model-object to response is pretty easy...

my concern is that if this enabled by default this can lead to accidental fields exposure (like if you output auth.User queryset - it will as well output passwords - something you do not really want)

maybe as a solution can be also some `unsafe` argument that will force users to think twice about it:

```Python
api.default_responses(unsafe_all=True)
```

**Comment by gmso** [comment]
I see, that would be security pitfall. And one easy to fall into, if the default is so permissive. I understand now why you thought about defining default fields or excluded fields.

With that idea in mind, how about something like this:
```Python
api.default_responses(
    allowed_fields={"username",},
    excluded_fields={"password","email"}
)
```

This would only need to be defined once, after initializing the `api = NinjaApi()` object. Without calling this function, an exception would be raised if trying to serialize a `QuerySet` or a model instance. The `excluded_fields` would take preference over `allowed_fields`, to make strict mode the default.

For example, with the following definition:
```Python
api.default_responses(allowed_fields={"username",})
```

when returning `auth.User.objects.get(pk=1)` from a view, we would get this (instead of all the fields):
```json
{
  "username": "admin_user"
}
```

and with the following definition:
```Python
api.default_responses(
    excluded_fields={"password","email","last_login","first_name","last_name"}
)
```

we would get this response:
```json
{
  "id": 1,
  "is_superuser": true,
  "username": "admin_user",
  "is_staff": true,
  "is_active": true,
  "date_joined": "2022-01-03T14:06:16Z"
}
```

If `allowed_fields` and `excluded_fields` have a conflict, the exclusion wins. So this:
```Python
api.default_responses(
    allowed_fields={"username",},
    excluded_fields={"username",},
)
```

returns this:
```json
{}
```

This definition would apply globally to all Models equally. If different `default_responses` should be set for different models individually, then this solution should be obviously changed.

**Comment by wu-clan** [comment]
Hi, I now use the customized schema as a different return, because it can automatically parse the returned data(Especially foreignkey). This is Discussions: https://github.com/vitalik/django-ninja/discussions/453#discussioncomment-2816756
I make a little point, for `django-ninja` There is a way `create_schema()`, It is very easy to use, but this is a more advanced (and less safe) method - please use it carefully. It's documented.
I don't know if you've seen `tortoise-orm`, It has a way `pydantic_model_creator()`, They are very similar, but for `pydantic_model_creator()` created model it has some return methods to use as response data, like: `from_tortoise_orm()`, `from_queryset_single()`, `from_queryset()`... I think I can get some inspiration from this. But in this case, `create_schema()` will be the focus, need to follow up on its security, and remain as compatible as before, like in the discussions, otherwise my project will make too many changes, or not just me.
