### ISSUE TITLE
cache for api?

### ISSUE THREAD

**Issue by jet10000** [vitalik/django-ninja#286]
@cache_page

Can I use @cache_page on the api?

**Comment by vitalik** [comment]
@jet10000 

the default `cache_page` decorator from django will not work (since it shadows function arguments)

what you can do is either enable per site caching with middleware
https://docs.djangoproject.com/en/3.2/topics/cache/#the-per-site-cache

or create custom decorator (with using `@wraps`):

pseudocode:

```Python
from functools import wraps
from django.core.cache import cache as django_cache


def cache(f):
    @wraps(f)
    def wrapper(request, *args, **kwargs):
        key  = `your key from request`
        result = django_cache.get(key)
        if result:
             return result
        result = f(request, *args, **kwargs)
        django_cache.set(key, result, timeout=30)
        return result

    return wrapper

#.....

@api.get('/test')
@cache
def my_function(request, foo: int):
    return ...
```
